server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# 日志级别
logging:
  level:
    com.hackathon: debug
    org.hibernate.SQL: debug
